//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DirectoryMonitorService
{
    using System;
    using System.Collections.Generic;
    
    public partial class TCompany
    {
        public int CompanyId { get; set; }
        public string CompanyName { get; set; }
        public string ContactPerson { get; set; }
        public decimal Overdraft { get; set; }
        public string VATNo { get; set; }
        public string RegNo { get; set; }
        public int OfficerOnDutyId { get; set; }
        public bool CanPayCash { get; set; }
        public string ICFXIdentity { get; set; }
        public bool UseOmnibus { get; set; }
        public bool CanPayUSD { get; set; }
        public decimal USDCommPerc { get; set; }
        public bool CanPayBWP { get; set; }
        public decimal BWPCommPerc { get; set; }
        public decimal TotalMarginZARPayment { get; set; }
        public bool Active { get; set; }
        public string Country { get; set; }
        public Nullable<System.DateTime> RegistrationDate { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public string EmailAddress { get; set; }
        public bool isNewsLetterSubscribed { get; set; }
        public string CompanyCreatedBy { get; set; }
        public string ContactPersonTelNo { get; set; }
        public bool OdoMeterReadingRequired { get; set; }
        public Nullable<System.DateTime> AutoRevalueDateTime { get; set; }
        public bool AutoReval { get; set; }
        public string AutoRevalUserName { get; set; }
        public bool PrepaidAccount { get; set; }
        public bool ReservedFundsActive { get; set; }
        public bool CheckBankAccountFirst { get; set; }
        public bool RecalcParkingOrders { get; set; }
        public int AutoCancelPendingOrders { get; set; }
        public string ClientAPIKey { get; set; }
        public bool DriverCanCreateOrder { get; set; }
        public byte[] LastUpdated { get; set; }
        public bool TestCompany { get; set; }
        public string Street { get; set; }
        public string Suburb { get; set; }
        public string City { get; set; }
        public bool IncreasedPINSecurity { get; set; }
    }
}
