//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DirectoryMonitorService
{
    using System;
    using System.Collections.Generic;
    
    public partial class TDeposit
    {
        public int DepositId { get; set; }
        public int CompanyId { get; set; }
        public string Ccy { get; set; }
        public decimal Amount { get; set; }
        public System.DateTime DepositDate { get; set; }
        public string UserName { get; set; }
        public int BankStatementId { get; set; }
        public bool SwiftVerified { get; set; }
        public bool DepositVerified { get; set; }
        public string SwiftVerifiedBy { get; set; }
        public Nullable<System.DateTime> SwiftVerifiedTime { get; set; }
        public string DepositedIntoBankName { get; set; }
        public string DepositVerifiedBy { get; set; }
        public Nullable<System.DateTime> DepositVerifiedTime { get; set; }
        public string ReferenceUsed { get; set; }
        public bool Declined { get; set; }
        public string DeclineReason { get; set; }
        public Nullable<System.DateTime> DeclineDateTime { get; set; }
        public bool IsCorrection { get; set; }
        public string AssociatedAccount { get; set; }
        public Nullable<System.DateTime> ActualVerifiedTime { get; set; }
        public string DepositedIntoBankName2 { get; set; }
        public string AssociatedAccount2 { get; set; }
        public int TFBankStatmentId { get; set; }
        public Nullable<System.DateTime> UserVerifiedTimeStamp { get; set; }
        public byte[] LastUpdated1 { get; set; }
        public string AllocatedToUserName { get; set; }
        public Nullable<System.DateTime> AllocatedToUserTime { get; set; }
    }
}
