//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DirectoryMonitorService
{
    using System;
    using System.Collections.Generic;
    
    public partial class TMock
    {
        public int DepositId { get; set; }
        public string AccountNumber { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public decimal DepositAmount { get; set; }
        public System.DateTime DateReceived { get; set; }
    }
}
